<?xml version="1.0" encoding="utf-8"?><Database Name="Coffee_POS" Class="Coffee_POSDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=LAPTOP-QFUA5EK6\SQLEXPRESS;Initial Catalog=Coffee_POS;Integrated Security=True" SettingsObjectName="CoffeePOS_System.Properties.Settings" SettingsPropertyName="Coffee_POSConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Categories" Member="Categories">
    <Type Name="Category">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Guid" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Status" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Association Name="Category_Product" Member="Products" ThisKey="Guid" OtherKey="CategoryGuid" Type="Product" />
    </Type>
  </Table>
  <Table Name="dbo.Users" Member="Users">
    <Type Name="User">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Guid" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Status" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="Role" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="UserCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Orders" Member="Orders">
    <Type Name="Order">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Guid" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ProductGuid" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="OrderDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Qty" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Price" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="TotalPrice" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="OrderBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="OrderFrom" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PaidBy" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="PaidAmount" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="ChangeAmount" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Status" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="OrderByCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="Product_Order" Member="Product" ThisKey="ProductGuid" OtherKey="Guid" Type="Product" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Products" Member="Products">
    <Type Name="Product">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Guid" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Price" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Remark" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="ImagePath" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="StockCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ImportDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Status" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="CategoryGuid" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Association Name="Product_Order" Member="Orders" ThisKey="Guid" OtherKey="ProductGuid" Type="Order" />
      <Association Name="Category_Product" Member="Category" ThisKey="CategoryGuid" OtherKey="Guid" Type="Category" IsForeignKey="true" />
    </Type>
  </Table>
</Database>